### ISSUE TITLE
sql_firewall and pgbench -i

### ISSUE THREAD

**Issue by MasaoFujii** [uptimejp/sql_firewall#11] opened 2015-08-31 03:08 UTC
Hi,

When I ran the following steps, I got unexpected warning messages.
Is this a bug? Or am I missing something?
1. Set sql_firewall.firewall to learning
2. Run pgbench -i
3. Set sql_firewall.firewall to permissive
4. Run pgbench -i

The last call of pgbench -i caused the following warning messages.

  WARNING: Prohibited SQL statement

BTW, I performend the above steps by executing the following
shell script.

```
bin/pg_ctl -D data stop -m f
rm -rf data

bin/initdb -D data --no-locale --encoding=UTF8
echo "shared_preload_libraries = 'sql_firewall'" >> data/postgresql.conf
echo "sql_firewall.firewall = 'disabled'" >> data/postgresql.conf

bin/pg_ctl -D data start -w
bin/psql <<EOF
CREATE EXTENSION sql_firewall;
ALTER SYSTEM SET sql_firewall.firewall = 'learning';
EOF

bin/pg_ctl -D data restart -w
bin/pgbench -i

bin/psql <<EOF
SELECT * FROM sql_firewall.sql_firewall_statements;
ALTER SYSTEM SET sql_firewall.firewall = 'permissive';
EOF

bin/pg_ctl -D data restart -w
bin/pgbench -i
```

Regards,

**Comment by snaga** [comment] 2015-08-31 08:41
Thanks for the report.
I could reproduce that, and  I found that INSERT statements raise that warnings.
I'm working on it.

```
#!/bin/sh

PGHOME=$HOME/usr/pgsql-9.4
PATH=$PGHOME/bin:$PATH
export PGHOME PATH

pg_ctl -D data stop -m f
rm -rf data

initdb -D data --no-locale --encoding=UTF8
echo "shared_preload_libraries = 'sql_firewall'" >> data/postgresql.conf
echo "sql_firewall.firewall = 'disabled'" >> data/postgresql.conf
echo "log_min_error_statement = warning" >> data/postgresql.conf

pg_ctl -D data start -w
psql postgres<<EOF
CREATE EXTENSION sql_firewall;
SHOW sql_firewall.firewall;
ALTER SYSTEM SET sql_firewall.firewall = 'learning';
SHOW sql_firewall.firewall;
EOF

pg_ctl -D data restart -w
pgbench -i postgres

psql postgres<<EOF
SELECT * FROM sql_firewall.sql_firewall_statements;
SHOW sql_firewall.firewall;
ALTER SYSTEM SET sql_firewall.firewall = 'permissive';
SHOW sql_firewall.firewall;
EOF

pg_ctl -D data restart -w
pgbench -i postgres

psql postgres<<EOF
SHOW sql_firewall.firewall;
EOF

```

```
$ sh test.sh
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down.....LOG:  database system is shut down
LOG:  sql_firewall file "pg_stat/sql_firewall_statements.stat" has been updated.
 done
server stopped
The files belonging to this database system will be owned by user "snaga".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D data
or
    pg_ctl -D data -l logfile start

waiting for server to start....LOG:  database system was shut down at 2015-08-31 17:36:37 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
CREATE EXTENSION
 sql_firewall.firewall
-----------------------
 disabled
(1 row)

ALTER SYSTEM
 sql_firewall.firewall
-----------------------
 disabled
(1 row)

LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down....LOG:  database system is shut down
LOG:  sql_firewall file "pg_stat/sql_firewall_statements.stat" has been updated.
 done
server stopped
waiting for server to start....LOG:  database system was shut down at 2015-08-31 17:36:40 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
NOTICE:  table "pgbench_history" does not exist, skipping
NOTICE:  table "pgbench_tellers" does not exist, skipping
NOTICE:  table "pgbench_accounts" does not exist, skipping
NOTICE:  table "pgbench_branches" does not exist, skipping
creating tables...
100000 of 100000 tuples (100%) done (elapsed 0.20 s, remaining 0.00 s).
vacuum...
set primary keys...
done.
 userid |  queryid   |                                                     query                                                     | calls
--------+------------+---------------------------------------------------------------------------------------------------------------+-------
     10 | 2417543957 | drop table if exists pgbench_history                                                                          |     1
     10 | 3921192557 | alter table pgbench_accounts add primary key (aid)                                                            |     1
     10 | 3464398693 | alter table pgbench_branches add primary key (bid)                                                            |     1
     10 |  415251803 | truncate pgbench_accounts                                                                                     |     1
     10 | 2042960798 | create table pgbench_history(tid int,bid int,aid    int,delta int,mtime timestamp,filler char(22))            |     1
     10 |  347448438 | vacuum analyze pgbench_branches                                                                               |     1
     10 | 2312510646 | create table pgbench_accounts(aid    int not null,bid int,abalance int,filler char(84)) with (fillfactor=100) |     1
     10 | 1868163425 | commit                                                                                                        |     2
     10 | 1639697065 | drop table if exists pgbench_branches                                                                         |     1
     10 |  355420951 | vacuum analyze pgbench_accounts                                                                               |     1
     10 | 1044785669 | drop table if exists pgbench_tellers                                                                          |     1
     10 | 3436081297 | insert into pgbench_branches(bid,bbalance) values(?,?)                                                        |     1
     10 |  181165670 | drop table if exists pgbench_accounts                                                                         |     1
     10 | 2820971117 | vacuum analyze pgbench_history                                                                                |     1
     10 | 1776614652 | alter table pgbench_tellers add primary key (tid)                                                             |     1
     10 |  387008091 | vacuum analyze pgbench_tellers                                                                                |     1
     10 | 3091166733 | create table pgbench_branches(bid int not null,bbalance int,filler char(88)) with (fillfactor=100)            |     1
     10 |  975326546 | insert into pgbench_tellers(tid,bid,tbalance) values (?,?,?)                                                  |    10
     10 | 4050214184 | copy pgbench_accounts from stdin                                                                              |     1
     10 |  821356254 | create table pgbench_tellers(tid int not null,bid int,tbalance int,filler char(84)) with (fillfactor=100)     |     1
     10 | 2111245140 | begin                                                                                                         |     2
(21 rows)

 sql_firewall.firewall
-----------------------
 learning
(1 row)

ALTER SYSTEM
 sql_firewall.firewall
-----------------------
 learning
(1 row)

LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down.....LOG:  database system is shut down
LOG:  sql_firewall file "pg_stat/sql_firewall_statements.stat" has been updated.
 done
server stopped
waiting for server to start....LOG:  database system was shut down at 2015-08-31 17:36:44 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_branches(bid,bbalance) values(1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_branches(bid,bbalance) values(1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (1,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (1,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (2,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (2,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (3,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (3,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (4,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (4,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (5,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (5,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (6,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (6,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (7,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (7,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (8,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (8,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (9,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (9,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (10,1,0)
WARNING:  Prohibited SQL statement
WARNING:  Prohibited SQL statement
STATEMENT:  insert into pgbench_tellers(tid,bid,tbalance) values (10,1,0)
WARNING:  Prohibited SQL statement
creating tables...
100000 of 100000 tuples (100%) done (elapsed 0.20 s, remaining 0.00 s).
vacuum...
set primary keys...
done.
 sql_firewall.firewall
-----------------------
 permissive
(1 row)

$
```

**Comment by snaga** [comment] 2015-09-01 03:19
I got the reason.
QueryId could be changed when oid of the table gets changed,
because queryid calculation includes table oid instead of the table name.

https://github.com/uptimejp/sql_firewall/blob/develop/sql_firewall.c#L2784

And "pgbench -i" drops and creates those tables on initializing,
so those table oids get changed, and the query ids could be also changed.

This is not a bug (so far), but needs to be considered in the future enhancement.

Here is a script to reproduce that.

```
#!/bin/sh

PGHOME=/usr/pgsql-9.4
PATH=$PGHOME/bin:$PATH
export PGHOME PATH

pg_ctl -D data stop -m f
rm -rf data

initdb -D data --no-locale --encoding=UTF8
echo "shared_preload_libraries = 'sql_firewall'" >> data/postgresql.conf
echo "sql_firewall.firewall = 'disabled'" >> data/postgresql.conf
echo "log_min_error_statement = warning" >> data/postgresql.conf
echo "client_min_messages = debug1" >> data/postgresql.conf

pg_ctl -D data start -w
psql postgres<<EOF
CREATE EXTENSION sql_firewall;
CREATE TABLE t1 ( uid INTEGER PRIMARY KEY );
ALTER SYSTEM SET sql_firewall.firewall = 'learning';
EOF

pg_ctl -D data restart -w

psql postgres<<EOF
INSERT INTO t1 VALUES ( 100 );
ALTER SYSTEM SET sql_firewall.firewall = 'permissive';
EOF

pg_ctl -D data restart -w

psql postgres<<EOF
-- Pass.
INSERT INTO t1 VALUES ( 200 );

SELECT * FROM sql_firewall.sql_firewall_statements;

DROP TABLE t1;
CREATE TABLE t1 ( uid INTEGER PRIMARY KEY );

-- Warning.
INSERT INTO t1 VALUES ( 200 );
EOF
```

**Comment by snaga** [comment] 2015-09-01 03:48
Just created new issue #13 to clarify the issue, so closing this issue.
Thanks.

**Closed as completed by snaga** 2015-09-01 03:48 UTC
